# Generated by Django 6.0.1 on 2026-03-18 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="todoo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
